{
  "openapi": "3.1.0",
  "info": {
    "title": "Authentication",
    "version": "1.0",
    "description": "API Access Authentication",
    "contact": {
      "name": "Dimas Pondra Oktafianto",
      "email": "dimaspondrao@gmail.com"
    },
    "summary": "API Authentication"
  },
  "servers": [
    {
      "url": "http://foodmarket-backend.test/api",
      "description": "Local Dimas"
    }
  ],
  "paths": {
    "/register": {
      "post": {
        "summary": "Register Account",
        "operationId": "post-register",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "examples": {
                  "Success Registration": {
                    "value": {
                      "meta": {
                        "code": 200,
                        "status": "success",
                        "message": "Registered Successfully"
                      },
                      "data": {
                        "access_token": "1|nJL56m70y7LraEBsNMT61kUxw3pXqyg7NmyioYor",
                        "token_type": "Bearer",
                        "user": {
                          "id": 2,
                          "name": "Dimas",
                          "email": "test@mail.com",
                          "email_verified_at": null,
                          "current_team_id": null,
                          "profile_photo_path": null,
                          "address": "Indonesia",
                          "houseNumber": "20",
                          "phoneNumber": "0822345678",
                          "city": "Indonesia",
                          "roles": "USER",
                          "created_at": 1639219275,
                          "updated_at": "2021-12-11T10:41:15.000000Z",
                          "profile_photo_url": "https://ui-avatars.com/api/?name=Dimas&color=7F9CF5&background=EBF4FF"
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "headers": {},
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "examples": {
                  "Authentication Failed": {
                    "value": {
                      "meta": {
                        "code": 500,
                        "status": "error",
                        "message": "Authentication Failed"
                      },
                      "data": {
                        "message": "Something went wrong",
                        "error": {
                          "validator": {
                            "customMessages": [],
                            "fallbackMessages": [],
                            "customAttributes": [],
                            "customValues": [],
                            "excludeUnvalidatedArrayKeys": null,
                            "extensions": [],
                            "replacers": []
                          },
                          "response": null,
                          "status": 422,
                          "errorBag": "default",
                          "redirectTo": null
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "description": "API untuk register akun baru",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string"
                  },
                  "address": {
                    "type": "string"
                  },
                  "houseNumber": {
                    "type": "string"
                  },
                  "phoneNumber": {
                    "type": "string"
                  },
                  "city": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  },
                  "password_confirmation": {
                    "type": "string"
                  }
                },
                "required": [
                  "name",
                  "email",
                  "password",
                  "password_confirmation"
                ]
              }
            }
          },
          "description": ""
        },
        "x-internal": false,
        "tags": [
          "Register"
        ],
        "parameters": [
          {
            "schema": {
              "type": "string",
              "default": "application/json"
            },
            "in": "header",
            "name": "Accept",
            "required": true
          },
          {
            "schema": {
              "type": "string",
              "enum": [
                "application/x-www-form-urlencoded"
              ]
            },
            "in": "header",
            "name": "Content-Type",
            "required": true
          }
        ]
      },
      "parameters": []
    },
    "/login": {
      "post": {
        "summary": "Login",
        "operationId": "post-login",
        "responses": {
          "200": {
            "description": "OK",
            "headers": {},
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "examples": {
                  "Success Login": {
                    "value": {
                      "meta": {
                        "code": 200,
                        "status": "success",
                        "message": "Authenticated"
                      },
                      "data": {
                        "access_token": "2|fQn3pjbQQodNARHDpliJ7DV2cFIh5YpIGkd15GZO",
                        "token_type": "Bearer",
                        "user": {
                          "id": 2,
                          "name": "Dimas",
                          "email": "test@mail.com",
                          "email_verified_at": null,
                          "current_team_id": null,
                          "profile_photo_path": null,
                          "address": "Indonesia",
                          "houseNumber": "20",
                          "phoneNumber": "0822345678",
                          "city": "Indonesia",
                          "roles": "USER",
                          "created_at": 1639219275,
                          "updated_at": "2021-12-11T10:41:15.000000Z",
                          "profile_photo_url": "https://ui-avatars.com/api/?name=Dimas&color=7F9CF5&background=EBF4FF"
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "examples": {
                  "Login Failed": {
                    "value": {
                      "meta": {
                        "code": 500,
                        "status": "error",
                        "message": "Authentication Failed"
                      },
                      "data": {
                        "message": "Something went wrong",
                        "error": {
                          "validator": {
                            "customMessages": [],
                            "fallbackMessages": [],
                            "customAttributes": [],
                            "customValues": [],
                            "excludeUnvalidatedArrayKeys": null,
                            "extensions": [],
                            "replacers": []
                          },
                          "response": null,
                          "status": 422,
                          "errorBag": "default",
                          "redirectTo": null
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "tags": [
          "Login"
        ],
        "description": "API untuk login",
        "parameters": [
          {
            "schema": {
              "type": "string",
              "default": "application/json"
            },
            "in": "header",
            "name": "Accept",
            "required": true
          },
          {
            "schema": {
              "type": "string",
              "enum": [
                "application/x-www-form-urlencoded"
              ]
            },
            "in": "header",
            "name": "Content-Type",
            "required": true
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "email": {
                    "type": "string",
                    "example": "test@mail.com"
                  },
                  "password": {
                    "type": "string",
                    "example": "test1234"
                  }
                },
                "required": [
                  "email",
                  "password"
                ]
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {}
  },
  "tags": [
    {
      "name": "Login"
    },
    {
      "name": "Register"
    }
  ]
}